# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Permcop < Formula
  desc "A rule-based permission filter for Claude Code PreToolUse hooks."
  homepage "https://github.com/phobologic/permcop"
  version "0.4.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/phobologic/permcop/releases/download/v0.4.1/permcop_0.4.1_darwin_amd64.tar.gz"
      sha256 "810f7fe41638d0c39c458f1ed440a8dc85deb55159dec557fcf42ed0b3d88ad7"

      define_method(:install) do
        bin.install "permcop"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/phobologic/permcop/releases/download/v0.4.1/permcop_0.4.1_darwin_arm64.tar.gz"
      sha256 "dd8c9041a3d5824923ec00bcb731c16f0568796296568700c5391d79d0b78959"

      define_method(:install) do
        bin.install "permcop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/phobologic/permcop/releases/download/v0.4.1/permcop_0.4.1_linux_amd64.tar.gz"
      sha256 "00c2bc6755d1b6bfd7e14157f1150372aeb3dfe1cb9d24d2e442cd4224a7d07d"
      define_method(:install) do
        bin.install "permcop"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/phobologic/permcop/releases/download/v0.4.1/permcop_0.4.1_linux_arm64.tar.gz"
      sha256 "832b1fd8397747bce8e573b832c0213b8f704c80686072b81cb193c0d7d11b02"
      define_method(:install) do
        bin.install "permcop"
      end
    end
  end

  test do
    system "#{bin}/permcop version"
  end
end
