# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Permcop < Formula
  desc "A rule-based permission filter for Claude Code PreToolUse hooks."
  homepage "https://github.com/phobologic/permcop"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/phobologic/permcop/releases/download/v0.2.0/permcop_0.2.0_darwin_amd64.tar.gz"
      sha256 "b0f4db2a078f4689ce65af006512746365000f3ed1191493a7abe325df59c806"

      define_method(:install) do
        bin.install "permcop"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/phobologic/permcop/releases/download/v0.2.0/permcop_0.2.0_darwin_arm64.tar.gz"
      sha256 "cd031e0b0a12bbeaca72341027477084bd2ff07d519e9255b9b518d6a981238f"

      define_method(:install) do
        bin.install "permcop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/phobologic/permcop/releases/download/v0.2.0/permcop_0.2.0_linux_amd64.tar.gz"
      sha256 "f327032be5683555bc7b93fee8754c95f8aab0b5e3391cf3a1eb21c15dd75898"
      define_method(:install) do
        bin.install "permcop"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/phobologic/permcop/releases/download/v0.2.0/permcop_0.2.0_linux_arm64.tar.gz"
      sha256 "d759d62c2f024e1c667cf4ca9ba9385e0c2d98130d15013a6c46604ea81ac95b"
      define_method(:install) do
        bin.install "permcop"
      end
    end
  end

  test do
    system "#{bin}/permcop version"
  end
end
