# This file was generated by GoReleaser. DO NOT EDIT.
cask "repoguide" do
  name "repoguide"
  desc "Generate tree-sitter repository maps in TOON format"
  homepage "https://github.com/phobologic/repoguide"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "repoguide"

  on_macos do
    on_intel do
      url "https://github.com/phobologic/repoguide/releases/download/v#{version}/repoguide_#{version}_darwin_amd64.tar.gz"
      sha256 "6fa96092f4e3f53b6b5592b1d00b044799eca620762fab1f2e29cbada483e57d"
    end
    on_arm do
      url "https://github.com/phobologic/repoguide/releases/download/v#{version}/repoguide_#{version}_darwin_arm64.tar.gz"
      sha256 "f9cfd652f4cf98c7821909502de79f400a0ae305a5bff8111ab87cd5578181da"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/phobologic/repoguide/releases/download/v#{version}/repoguide_#{version}_linux_amd64.tar.gz"
      sha256 "696d9c5c8db60ee6799881207f9b541ac258c5aaed0cb891c0db2fc2d756d43c"
    end
    on_arm do
      url "https://github.com/phobologic/repoguide/releases/download/v#{version}/repoguide_#{version}_linux_arm64.tar.gz"
      sha256 "fccc957098e5647bfba49387b2d5484291cd3194929aa3f3fde0847660b75726"
    end
  end

  # No zap stanza required
end
