# This file was generated by GoReleaser. DO NOT EDIT.
cask "repoguide" do
  name "repoguide"
  desc "Generate tree-sitter repository maps in TOON format"
  homepage "https://github.com/phobologic/repoguide"
  version "1.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "repoguide"

  on_macos do
    on_intel do
      url "https://github.com/phobologic/repoguide/releases/download/v#{version}/repoguide_#{version}_darwin_amd64.tar.gz"
      sha256 "d13fcf295f741b28dc5b2dfeef92edb5c41e0720dc5e5a985d26e99fe57b61db"
    end
    on_arm do
      url "https://github.com/phobologic/repoguide/releases/download/v#{version}/repoguide_#{version}_darwin_arm64.tar.gz"
      sha256 "5df60fc6d34a18ec99b9d800d17088788c68659dcf21eebcf78d76a8eed332e7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/phobologic/repoguide/releases/download/v#{version}/repoguide_#{version}_linux_amd64.tar.gz"
      sha256 "fa193c5d0914de94853392c67ef6493ba6956113bdb36e537b72b99e05b4cd08"
    end
    on_arm do
      url "https://github.com/phobologic/repoguide/releases/download/v#{version}/repoguide_#{version}_linux_arm64.tar.gz"
      sha256 "ac38572f2aafb2e72d83bab28346178fac45f79d7e4fc25dd19f654a868fcbe0"
    end
  end

  # No zap stanza required
end
